# Lang
language: "en"

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Blog: /Blog
  About: /About

rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics: UA-54529135-2
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: "I Know Nothing"
description: "Mehran Baghi"
links:
  Blog: /Blog
  About: /About

# Info
archive_footer_content: 'Except As Otherwise Noted, The Content Of This Page Is Licensed Under The
<a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="license">CC-BY-SA 4.0 License</a>

And Code Samples Are Licensed Under The <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" rel="license">GPL 3.0 License</a>

Powered By <a href="https://hexo.io/">Hexo</a> Theme: <a href="https://github.com/geekplux/hexo-theme-typing">Typing</a>'

post_footer_content: 'Except As Otherwise Noted, The Content Of This Page Is Licensed Under The
<a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="license">CC-BY-SA 4.0 License</a>

And Code Samples Are Licensed Under The <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" rel="license">GPL 3.0 License</a>

Powered By <a href="https://hexo.io/">Hexo</a> Theme: <a href="https://github.com/geekplux/hexo-theme-typing">Typing</a>'
